export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Projects } from "./Projects"
export { default as Events } from "./Events"
export { default as Members } from "./Members"